### ISSUE TITLE
Variable "prototype" does not exist.

### ISSUE THREAD

**Issue by potibm** [tienvx/ux-collection-js#36]
Having a form type with ``'allow_add' => false,`` the twig template gives me the error message above.

I solved it by "extending" the template, overriding collection_js_accordion with

``
    <div class="collection-js-root" {% if prototype is defined %}data-prototype="{{ form_widget(prototype) | e }}" {% endif %}>
``

Seems to fix it.

**Comment by potibm** [comment]
Just a short notice: removing the data-prototype lead to unchanged return of the ordered items. After adding the prototype this worked...

**Comment by tienvx** [comment]
Hi @potibm . Thanks for reporting the issue.

It's fixed by https://github.com/tienvx/ux-collection-js/pull/37: always adding variable 'prototype'

Please test again by update to `v1.0.0-beta.4`

**Comment by potibm** [comment]
Seems to work just fine. Thanks!
